### ISSUE TITLE
Incompatible with Entity Model Features + Fresh Animations

### ISSUE THREAD

**Issue by BLUEChester** [mineblock11/Armorful#13]
It makes villagers and evokers eyes invisible, haven't tested it on any other mobs, but w/o this mod the issue is fixed.

**Comment by mpustovoi** [comment]
Must be fixed in latest EMF Release Candicates

**Comment by mineblock11** [comment]
Yeah, confirmed fixed in EMF RC

**Comment by Datbanana** [comment]
Using emf version 1.0.1 on minecraft 1.19.2 im still seeing a distinct lack of eyeballs on fresh animations illagers when this mod is enabled, so i feel this may not be a fixed issue (dunno for sure though yet though, i havnt checked without the rest of my modpack disabled)

![armorful on](https://github.com/mineblock11/Armorful/assets/42188186/ef1ebcf6-ba2a-4eb9-b95e-dd886273c697)

![no armorful](https://github.com/mineblock11/Armorful/assets/42188186/25cd5243-9c3e-4776-b54c-7efc3d32c2b1)


id also like to point out dogs not wanting to keep armor on while fresh animations is on, separate issue but i think it falls under the same umbrella?

![doggo](https://github.com/mineblock11/Armorful/assets/42188186/ed4cba0f-2947-4c13-a9f5-73c5cf6aa8d6)

**Comment by mpustovoi** [comment]
Yeah, I figured out that with Armorful and latest EMF pillagers are still broken. I haven't checked the dogs, but I guess they are too.
